# Generated by Django 2.2 on 2019-05-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0003_auto_20190510_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.CharField(default='#', max_length=500)),
                ('call', models.CharField(default='#', max_length=500)),
                ('mail', models.CharField(default='#', max_length=500)),
                ('visit', models.CharField(default='#', max_length=500)),
                ('copywrite', models.CharField(default='#', max_length=500)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translation',
            },
        ),
    ]
