# Generated by Django 2.2 on 2019-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0004_translations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='address_functional',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address_visual',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email_functional',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email_visual',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telephone_functional',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telephone_visual',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='call',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='copywrite',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='visit',
        ),
        migrations.AddField(
            model_name='footer',
            name='copywrite',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='telephone',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
