# Generated by Django 2.2 on 2019-06-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0005_auto_20190619_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhySumaksAcademy',
            new_name='About',
        ),
    ]
