# Generated by Django 2.2 on 2019-06-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0006_auto_20190620_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='_3d_printing_logo',
            new_name='printing_logo',
        ),
    ]
