# Generated by Django 2.2.6 on 2019-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0007_auto_20190620_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(default=0, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('PR', 'Participated'), ('SP', 'Successfully Participated'), ('DS', 'Distinction')], default='PR', max_length=255)),
                ('term', models.CharField(choices=[('Sum', 'Summer'), ('Fa', 'Fall'), ('Win', 'Winter')], default='Sum', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
