# Generated by Django 2.2.6 on 2019-12-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0008_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
