# Generated by Django 2.2.6 on 2020-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0009_delete_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='image1',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='website/'),
        ),
    ]
