# Generated by Django 2.2.6 on 2020-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0010_instructors_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='website/'),
        ),
    ]
