# Generated by Django 3.0.2 on 2020-01-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app_eng', '0012_auto_20200116_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='image1',
        ),
    ]
