# Generated by Django 2.2 on 2019-05-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesSchedules',
        ),
    ]
