# Generated by Django 2.2 on 2019-05-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0004_translations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='_3d_printing_logo',
            new_name='three_d_printing_logo',
        ),
    ]
