# Generated by Django 2.2 on 2019-06-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0005_auto_20190510_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='address_functional',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='email_functional',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='telephone_functional',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address_visual',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email_visual',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telephone_visual',
        ),
    ]
