# Generated by Django 2.2 on 2019-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0006_auto_20190619_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='rights',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
