# Generated by Django 2.2 on 2019-06-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0007_auto_20190619_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations',
            name='copywrite',
        ),
    ]
