# Generated by Django 2.2 on 2019-06-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0008_remove_translations_copywrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations',
            name='call',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='visit',
        ),
    ]
