# Generated by Django 2.2 on 2019-06-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0009_auto_20190619_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhySumaksAcademy',
            new_name='About',
        ),
    ]
