# Generated by Django 2.2.6 on 2019-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0011_certificates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='certificates',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='id_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='level',
            field=models.CharField(choices=[('PR', 'Participated'), ('SP', 'Successfully Participated'), ('DS', 'Distinction')], default='PR', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='semester',
            field=models.CharField(choices=[('Sum', 'Summer'), ('Fa', 'Fall'), ('Win', 'Winter')], default='Sum', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
