# Generated by Django 2.2.6 on 2019-11-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0012_auto_20191106_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='semester',
            new_name='term',
        ),
    ]
