# Generated by Django 2.2.6 on 2020-01-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0015_certificates_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='qr_code',
        ),
    ]
