# Generated by Django 3.0.2 on 2020-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0016_remove_certificates_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='website/'),
        ),
    ]
